import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import {Box,HStack, VStack, Text, Link,Heading} from '@chakra-ui/react';
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
        </div>
      <Box  mt={6} p="50px" >
            <HStack spacing={10} display={"flex"} alignItems="center" justifyContent="center"
            p="50px" color = "white"> 
            <VStack display={"flex"} alignItems="center" justifyContent="center" spacing={6} w="50%"> 
                <Heading size="xl">Get Amazing Products</Heading>
                    <Text fontSize={"24px"} textAlign={"justify"}>
                      Took a Look at some of the awesome products available on our market place at a very affordable and cheap prices.
                      Hurry and grab some awesome deals and offers too!!!
                    </Text>
                    <VStack  display={"flex"} justifyContent={"flex-end"} alignItems={"flex-end"} mt={5}>
                    <Link to="/dashboard">
                    
                    </Link>
                    </VStack>
            </VStack>
            </HStack>
            </Box>
            </main>
    </>
  );
}
